# Generated by Django 4.2.1 on 2023-05-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_date_alter_payment_pament_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='country',
            new_name='country_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 29, 10, 331733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 29, 10, 332730, tzinfo=datetime.timezone.utc)),
        ),
    ]
