# Generated by Django 4.2.1 on 2023-05-12 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_contactinfo_country_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 36, 46, 88378, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 36, 46, 89414, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.countries'),
        ),
    ]
