# Generated by Django 4.2.1 on 2023-05-12 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_country_contactinfo_country_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 33, 46, 202615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 17, 33, 46, 203611, tzinfo=datetime.timezone.utc)),
        ),
    ]
