# Generated by Django 4.2 on 2023-05-11 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 13, 17, 54, 650169, tzinfo=datetime.timezone.utc)),
        ),
    ]
