# Generated by Django 4.2 on 2023-05-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 13, 20, 56, 711198, tzinfo=datetime.timezone.utc)),
        ),
    ]
