# Generated by Django 4.2.1 on 2023-05-12 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_country_id_contactinfo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 22, 15, 57, 153253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_cvc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 22, 15, 57, 154251, tzinfo=datetime.timezone.utc)),
        ),
    ]
