# Generated by Django 4.2.1 on 2023-05-12 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_order_date_alter_payment_pament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 47, 5, 102185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 47, 5, 103222, tzinfo=datetime.timezone.utc)),
        ),
    ]
