# Generated by Django 4.2.1 on 2023-05-11 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_order_date_payment_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 15, 44, 39, 270283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 15, 44, 39, 272277, tzinfo=datetime.timezone.utc)),
        ),
    ]
