# Generated by Django 4.2.1 on 2023-05-11 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_order_date_alter_payment_pament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_csv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 16, 37, 47, 518578, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 16, 37, 47, 520573, tzinfo=datetime.timezone.utc)),
        ),
    ]
