# Generated by Django 4.2.1 on 2023-05-11 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_payment_card_csv_payment_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_csv',
            new_name='card_cvv',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 17, 24, 24, 587963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 17, 24, 24, 589956, tzinfo=datetime.timezone.utc)),
        ),
    ]
