# Generated by Django 4.2.1 on 2023-05-11 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_rename_card_csv_payment_card_cvv_payment_card_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_cvv',
            new_name='card_cvc',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 19, 23, 29, 985699, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 19, 23, 29, 986696, tzinfo=datetime.timezone.utc)),
        ),
    ]
