# Generated by Django 4.2.1 on 2023-05-12 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_countries_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.countries'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 14, 49, 43, 675045, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pament_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 14, 49, 43, 675045, tzinfo=datetime.timezone.utc)),
        ),
    ]
