# Generated by Django 4.2 on 2023-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
