# Generated by Django 4.2 on 2023-05-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
