# Generated by Django 4.2 on 2023-05-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_pizzas_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas'),
        ),
        migrations.AddField(
            model_name='sales',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas'),
        ),
        migrations.CreateModel(
            name='PizzaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=9999)),
                ('pizza', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas')),
            ],
        ),
    ]
