# Generated by Django 4.2 on 2023-05-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_pizzaimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='id',
        ),
        migrations.AlterField(
            model_name='prices',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.pizzas'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.pizzas'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.pizzas'),
        ),
    ]
