# Generated by Django 4.2 on 2023-05-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_prices_id_remove_ratings_id_remove_sales_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='price_large',
            field=models.FloatField(default=3999.0),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='price_medium',
            field=models.FloatField(default=2999.0),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='price_small',
            field=models.FloatField(default=1999.0),
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
