# Generated by Django 4.2 on 2023-05-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_pizzas_price_large_pizzas_price_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='pizza',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.pizzas'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='pizza',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.pizzas'),
        ),
    ]
