# Generated by Django 4.2 on 2023-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_pizzas_price_large_alter_pizzas_price_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
