# Generated by Django 4.2 on 2023-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_pizzas_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='price_large',
            field=models.IntegerField(default=3199),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='price_medium',
            field=models.IntegerField(default=2199),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='price_small',
            field=models.IntegerField(default=1199),
        ),
    ]
