# Generated by Django 4.2 on 2023-05-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_pizzas_price_large_alter_pizzas_price_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='pizza',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas'),
        ),
    ]
