# Generated by Django 4.2 on 2023-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_categories_pizza_categories_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='categories', to='menu.pizzas'),
        ),
    ]
