# Generated by Django 4.2 on 2023-05-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_remove_categories_pizza_pizzas_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaImage',
            new_name='Pizza_image',
        ),
        migrations.CreateModel(
            name='Pizza_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.categories')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas')),
            ],
        ),
    ]
