# Generated by Django 4.2 on 2023-05-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_rename_pizzaimage_pizza_image_pizza_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza_image',
            new_name='PizzaImage',
        ),
    ]
