# Generated by Django 4.2 on 2023-05-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_sales_sales_delete_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('pizza', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.pizzas')),
            ],
        ),
    ]
