# Generated by Django 4.2 on 2023-05-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_ratings_id_remove_ratings_pizza_ratings_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
