# Generated by Django 4.2 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_delete_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pizzas',
            name='ratings',
            field=models.ManyToManyField(related_name='pizzas', to='menu.ratings'),
        ),
    ]
