# Generated by Django 4.2 on 2023-05-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_ratings_pizzas_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzas',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
