# Generated by Django 4.2.1 on 2023-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_rename_date_added_pizzas_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pizzas',
            name='toppings',
            field=models.ManyToManyField(related_name='pizzas', to='menu.toppings'),
        ),
    ]
