# Generated by Django 4.2.1 on 2023-05-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_toppings_pizzas_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Pizzas',
            new_name='Pizza',
        ),
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Topping',
        ),
    ]
