# Generated by Django 4.2 on 2023-05-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_rename_toppings_category_rename_pizzas_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='categories',
            field=models.ManyToManyField(related_name='pizzas', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='pizzas', to='menu.topping'),
        ),
        migrations.AlterField(
            model_name='pizza_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
    ]
