# Generated by Django 4.2 on 2023-05-07 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_alter_pizza_categories_alter_pizza_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 5, 7)),
        ),
    ]
