# Generated by Django 4.2 on 2023-05-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_pizza_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.rating')),
            ],
        ),
    ]
