# Generated by Django 4.2 on 2023-05-10 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_pizza_topping_pizza_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
