# Generated by Django 4.2 on 2023-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_alter_pizza_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='is_new',
        ),
    ]
