# Generated by Django 4.2 on 2023-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_remove_pizza_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
