# Generated by Django 4.2 on 2023-05-11 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_pizza_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 13, 0, 12, 904377, tzinfo=datetime.timezone.utc)),
        ),
    ]
